#!/bin/bash
# Ops B2B Booking Detail Risk Info - Sample curl Commands
# 
# This script demonstrates the curl commands used to test the ops B2B booking detail endpoint
# for finance_flags and credit_status functionality.

BASE_URL="https://ops-excellence-10.preview.emergentagent.com"

echo "=== OPS B2B BOOKING DETAIL RISK INFO - CURL EXAMPLES ==="
echo ""

# Step 1: Login as admin to get JWT token
echo "1. Admin Login:"
echo "curl -X POST $BASE_URL/api/auth/login \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"email\": \"admin@acenta.test\", \"password\": \"admin123\"}'"
echo ""

# Sample response (token masked)
echo "Response:"
echo "{"
echo "  \"access_token\": \"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9...[MASKED]\","
echo "  \"token_type\": \"bearer\","
echo "  \"user\": {"
echo "    \"id\": \"admin_user_id\","
echo "    \"email\": \"admin@acenta.test\","
echo "    \"organization_id\": \"org_ops_close_idem\","
echo "    \"roles\": [\"admin\", \"super_admin\"]"
echo "  }"
echo "}"
echo ""

# Step 2: Test booking with near_limit finance_flags
echo "2. GET Booking Detail with near_limit finance_flags:"
echo "curl -X GET $BASE_URL/api/ops/bookings/696eadb2b39d833bec987424 \\"
echo "  -H 'Authorization: Bearer [JWT_TOKEN]'"
echo ""

echo "Response:"
echo "{"
echo "  \"booking_id\": \"696eadb2b39d833bec987424\","
echo "  \"agency_id\": \"test_agency_id\","
echo "  \"status\": \"CONFIRMED\","
echo "  \"payment_status\": \"unpaid\","
echo "  \"currency\": \"EUR\","
echo "  \"amounts\": {"
echo "    \"net\": 100.0,"
echo "    \"sell\": 115.0,"
echo "    \"breakdown\": {"
echo "      \"base\": 100.0,"
echo "      \"markup_amount\": 15.0,"
echo "      \"discount_amount\": 0.0"
echo "    }"
echo "  },"
echo "  \"customer\": {"
echo "    \"full_name\": \"Test Near_Limit Customer\","
echo "    \"email\": \"near_limit@test.com\","
echo "    \"phone\": \"+90 555 123 4567\""
echo "  },"
echo "  \"quote_id\": \"qt_test_near_limit_0fb4cca2\","
echo "  \"finance_flags\": {"
echo "    \"near_limit\": true,"
echo "    \"over_limit\": false"
echo "  },"
echo "  \"credit_status\": \"near_limit\""
echo "}"
echo ""

# Step 3: Test booking with over_limit finance_flags
echo "3. GET Booking Detail with over_limit finance_flags:"
echo "curl -X GET $BASE_URL/api/ops/bookings/696eadb3b39d833bec987428 \\"
echo "  -H 'Authorization: Bearer [JWT_TOKEN]'"
echo ""

echo "Response:"
echo "{"
echo "  \"booking_id\": \"696eadb3b39d833bec987428\","
echo "  \"agency_id\": \"test_agency_id\","
echo "  \"status\": \"CONFIRMED\","
echo "  \"payment_status\": \"unpaid\","
echo "  \"currency\": \"EUR\","
echo "  \"amounts\": {"
echo "    \"net\": 100.0,"
echo "    \"sell\": 115.0"
echo "  },"
echo "  \"customer\": {"
echo "    \"full_name\": \"Test Over_Limit Customer\","
echo "    \"email\": \"over_limit@test.com\","
echo "    \"phone\": \"+90 555 123 4567\""
echo "  },"
echo "  \"quote_id\": \"qt_test_over_limit_b0c2a009\","
echo "  \"finance_flags\": {"
echo "    \"near_limit\": false,"
echo "    \"over_limit\": true"
echo "  },"
echo "  \"credit_status\": \"over_limit\""
echo "}"
echo ""

# Step 4: Test booking with no finance_flags (legacy)
echo "4. GET Booking Detail with no finance_flags (legacy):"
echo "curl -X GET $BASE_URL/api/ops/bookings/696eadb4b39d833bec98742b \\"
echo "  -H 'Authorization: Bearer [JWT_TOKEN]'"
echo ""

echo "Response:"
echo "{"
echo "  \"booking_id\": \"696eadb4b39d833bec98742b\","
echo "  \"agency_id\": null,"
echo "  \"status\": \"CONFIRMED\","
echo "  \"payment_status\": \"paid\","
echo "  \"currency\": \"EUR\","
echo "  \"amounts\": {"
echo "    \"net\": 100.0,"
echo "    \"sell\": 115.0"
echo "  },"
echo "  \"customer\": {"
echo "    \"full_name\": \"Legacy Test Customer\","
echo "    \"email\": \"legacy@test.com\","
echo "    \"phone\": \"+90 555 999 8888\""
echo "  },"
echo "  \"quote_id\": null,"
echo "  \"finance_flags\": {},"
echo "  \"credit_status\": \"ok\""
echo "}"
echo ""

echo "=== TEST RESULTS SUMMARY ==="
echo "✅ PASS: near_limit scenario - finance_flags.near_limit=true → credit_status='near_limit'"
echo "✅ PASS: over_limit scenario - finance_flags.over_limit=true → credit_status='over_limit'"  
echo "✅ PASS: no flags scenario - empty finance_flags → credit_status='ok'"
echo ""
echo "All three scenarios successfully tested and verified!"