from __future__ import annotations

FEATURE_DASHBOARD = "dashboard"
FEATURE_PARTNERS = "partners"
FEATURE_B2B = "b2b"
FEATURE_ACCOUNTING = "accounting"
FEATURE_WEBPOS = "webpos"
FEATURE_REPORTS = "reports"
FEATURE_INVENTORY = "inventory"
FEATURE_CRM = "crm"
FEATURE_OPS = "ops"

ALL_FEATURE_KEYS = [
  FEATURE_DASHBOARD,
  FEATURE_PARTNERS,
  FEATURE_B2B,
  FEATURE_ACCOUNTING,
  FEATURE_WEBPOS,
  FEATURE_REPORTS,
  FEATURE_INVENTORY,
  FEATURE_CRM,
  FEATURE_OPS,
]
