// Centralised admin navigation definition (FAZ 0)
// This describes sections + items; AppShell decides how to render.

export const adminNav = [
  {
    label: "Admin",
    children: [
      { label: "B2B Dashboard", path: "/app/admin/b2b/dashboard" },
      { label: "Acentalar", path: "/app/admin/agencies" },
      { label: "Oteller", path: "/app/admin/hotels" },
      { label: "Turlar", path: "/app/admin/tours" },
      { label: "Link Yönetimi", path: "/app/admin/links" },
      { label: "CMS Sayfaları", path: "/app/admin/cms/pages" },
      { label: "Kampanyalar", path: "/app/admin/campaigns" },
      { label: "Partnerler", path: "/app/admin/partners" },
      { label: "B2B Marketplace", path: "/app/admin/b2b/marketplace" },
      { label: "Katalog", path: "/app/admin/catalog" },
      { label: "Otel Kataloğu", path: "/app/admin/catalog/hotels" },
      { label: "Fiyatlandırma", path: "/app/admin/pricing" },
      { label: "Kuponlar", path: "/app/admin/coupons" },
      { label: "Onay Görevleri", path: "/app/admin/approvals" },
      { label: "WebPOS", path: "/app/finance/webpos", requiredFeature: "webpos" },
      { label: "Finans / İadeler", path: "/app/admin/finance/refunds" },
      { label: "Exposure & Aging (Acenta)", path: "/app/admin/finance/exposure" },
      { label: "B2B Acenteler", path: "/app/admin/finance/b2b-agencies" },
      { label: "B2B Funnel", path: "/app/admin/b2b/funnel" },
      { label: "B2B Duyuruları", path: "/app/admin/b2b/announcements" },
      { label: "Finans / Mutabakat", path: "/app/admin/finance/settlements" },
      { label: "Ops / B2B", path: "/app/admin/ops/b2b" },
      { label: "Tenant Özellikleri", path: "/app/admin/tenant-features" },
      { label: "Audit Log", path: "/app/admin/audit-logs" },
      { label: "Revenue Analytics", path: "/app/admin/analytics" },
      { label: "Tenant Saglik", path: "/app/admin/tenant-health" },
    ],
  },
  {
    label: "Risk & Matches",
    children: [
      { label: "Match Listesi", path: "/app/admin/matches" },
      { label: "Match Risk Raporu", path: "/app/admin/reports/match-risk" },
      { label: "Match Risk Trendleri", path: "/app/admin/reports/match-risk-trends" },
      { label: "Match Alert Politikaları", path: "/app/admin/settings/match-alerts" },
      { label: "Aksiyon Politikaları", path: "/app/admin/settings/action-policies" },
      { label: "Export Çalıştırma", path: "/app/admin/exports" },
    ],
  },
  {
    label: "Operasyonel Mükemmellik",
    children: [
      { label: "Sistem Yedekleri", path: "/app/admin/system-backups" },
      { label: "Veri Bütünlüğü", path: "/app/admin/system-integrity" },
      { label: "Sistem Metrikleri", path: "/app/admin/system-metrics" },
      { label: "Sistem Hataları", path: "/app/admin/system-errors" },
      { label: "Çalışma Süresi", path: "/app/admin/system-uptime" },
      { label: "Olay Yönetimi", path: "/app/admin/system-incidents" },
      { label: "Go-Live Kontrolü", path: "/app/admin/preflight" },
      { label: "Ops Runbook", path: "/app/admin/runbook" },
      { label: "Performans Paneli", path: "/app/admin/perf-dashboard" },
    ],
  },
];
